spring:
  application:
    name: ms-clientes

  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true


  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: grupo-ms-clientes
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      type: single
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.bank.ms_clientes: DEBUG